package gifterland3.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * An entity Foodstore composed by three fields (id, email, name).
 * (Должно быть описание магазина,
 * телефон,
 * адрес,
 * условия доставки,
 * ФИО владельца,
 * картинка)
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author borrowed
 */
@Entity
@Table(name = "foodstores") //Capitalize?
public class Foodstore {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

    // The foodservice's name
    @NotNull
    private String name;
  
  // The foodservice's email
  @NotNull
  private String email;
  


    private String description;
    //private String deliveryCondition;TODO: case

    private String ownerName;
    private String ownerSurname;
    private String ownerPatronymic;

    private String address;
    private String phone;

//    //private Blob image;
//    //@Column(name="image")
//    @Lob
//    private Blob image;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Foodstore() { }

  public Foodstore(long id) {
    this.id = id;
  }
  
  public Foodstore(String email, String name) {
    this.email = email;
    this.name = name;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getEmail() {
    return email;
  }
  
  public void setEmail(String value) {
    this.email = value;
  }
  
  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }
  
} // class Foodstore
